-- MySQL Script generated by MySQL Workbench
-- Ne 20. január 2019, 11:52:15 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sovygo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sovygo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sovygo` DEFAULT CHARACTER SET utf8 ;
USE `sovygo` ;

-- -----------------------------------------------------
-- Table `sovygo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sovygo`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(75) NOT NULL,
  `salt` VARCHAR(16) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `auth` VARCHAR(45) NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sovygo`.`lastlogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sovygo`.`lastlogin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `succes` CHAR NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lastlogin_1_idx` (`userid` ASC),
  CONSTRAINT `fk_lastlogin_1`
    FOREIGN KEY (`userid`)
    REFERENCES `sovygo`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sovygo`.`loginincident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sovygo`.`loginincident` (
  `idloginincident` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` CHAR(39) NULL,
  PRIMARY KEY (`idloginincident`),
  UNIQUE INDEX `idloginincident_UNIQUE` (`idloginincident` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- --------------------------------------------------
-- GRANT ALL PRIVILEGES ON sovygo.* TO ''@'localhost' IDENTIFIED BY '';
-- --------------------------------------------------